apiVersion: v1
kind: Pod
metadata:
 name: abc
spec:
 volumes:
 - name: myvol
   configMap:
     name: db-config-vol
 containers:
 - name: db
   image: 
   volumeMounts:
   - name: myvol
     mountPath: /data