apiVersion: apps/v1
kind: Deployment
metadata:
 name: mywebapp
# annotations:
#  kubernetes.io/change-cause: "This is my first version of application released on <DATE>"
spec:
 replicas: 5
 selector:
  matchLabels:
   app: data
 template:
  metadata:
   labels:
    app: data
  spec:
   containers:
   - name: abc
     image: quay.io/gauravkumar9130/production:v1