apiVersion: v1
kind: Pod
metadata:
 name: cache-pod
spec:
 volumes:
 - name: cache
   emptyDir: {}
 containers:
 - name: abc
   image: quay.io/gauravkumar9130/nginxdemo
   volumeMounts:
   - name: cache
     mountPath: /data/