apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv1
spec:
 storageClassName: pv1                        # label of storage
 accessModes:
 - ReadWriteMany
 capacity:
  storage: "1Gi"
 hostPath:                                # worker node specific storage in /host dir
  path: /myvoldata