apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv2
spec:
 storageClassName: pv2                        # label of storage
 accessModes:
 - ReadWriteMany
 capacity:
  storage: "2Gi"
 hostPath:                                # worker node specific storage in /host dir
  path: /myvoldata2