apiVersion: v1
kind: Pod
metadata:
 name: myapp-init
spec:
 volumes:
 - name: myvol
   emptyDir: {}
 containers:
 - name: main
   image: quay.io/gauravkumar9130/nginx
   volumeMounts:
   - name: myvol
     mountPath: /usr/share/nginx/html
 initContainers:
 - name: init
   image: quay.io/gauravkumar9130/ubuntu-git
   command: ["/bin/sh"]
   args: ["-c","git clone https://github.com/gauravkumar9130/webpage; cd webpage; mv * /website/"]
   volumeMounts:
   - name: myvol
     mountPath: /website