apiVersion: v1
kind: Pod
metadata:
 name: my-pv-pod
 spec:
  volumes:
  - name: myvol
    persistentVolumeCliam:
     claimNmae: pvc1
  containers:
  - name: abc
    image: quay.io/gauravkumar9130/nginxdemo
    volumeMounts:
    - name: myvol
      mountPath: /mycontainerdata