apiVersion: v1
kind: Pod
metadata:
 name: dev-pod
 namespace: production
spec:
 containers:
 - name: abc
   image: quay.io/gauravkumar9130/nginxdemo
   resources:
    requests:
         cpu: "1"
         memory: "1Gi"
    limits:
         cpu: "2"
         memory: "2Gi"