apiVersion: v1
kind: Pod
metadata:
 name: pod2
spec:
 containers:
 - name: c1
   image:  quay.io/gauravkumar9130/mywebapp
 tolerations:
 - key: env
   operator: Equal
   value: prod
   effect: NoSchedule